### ISSUE TITLE
User Password can be changed by arbitrary user without confirmation

### ISSUE THREAD

**Issue by K4tana** [Enterprize1/phishy-mailbox#73]
I discovered that the user password for any user can be changed by any other user without confirmation of the current password. Maybe add a field that requires input of the old password before being able to set a new one.

**Comment by Enterprize1** [comment]
This is intended to get around having to provide a password reset flow (and sending emails etc.). I could introduce a lightweight permission system, where only some users (including the initial one) have the right to reset passwords and everyone else only being able to change their own password. What do you think?

**Comment by K4tana** [comment]
Seems fair. This superuser/admin system might work as well, esp. considering that in some larger orgs they might want some feature like that anyways.
